---
    kind: pipeline
    type: docker
    name: default
    
    steps:
    - name: build
      image: fermiumlabs/latex-docker
      commands:
      - apt-key del "E298 A3A8 25C0 D65D FD57 CBB6 5171 6619 E084 DAB9"
      - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
      - apt-get update -yqq
      - apt-get install -yqq libcurl4-openssl-dev libssh2-1-dev curl  libxml2-dev libssl-dev imagemagick
      - Rscript -e "install.packages('curl',repos='https://cran.rstudio.com');"
      - Rscript -e "install.packages('here',repos='https://cran.rstudio.com');"
      - Rscript -e "install.packages('tidyverse',repos='https://cran.rstudio.com');"
      - Rscript -e "install.packages('gridExtra',repos='https://cran.rstudio.com');"
      - Rscript -e "install.packages('ggthemes',repos='https://cran.rstudio.com');"
      - Rscript -e "install.packages('ggpubr',repos='https://cran.rstudio.com');"
      - make clean
      - make zip

    - name: publish
      image: plugins/github-release
      settings:
        api_key:
          from_secret: github_token
        files: Exports/*
      when:
        event: tag