language: R
install:
  - sudo apt-get update
  - sudo apt-get -y install jq python-pip zip #used to get the last pandoc version
  - sudo apt-get -y remove pandoc #remove obsolete pandoc version
  - sudo pip install --upgrade pip
  - sudo pip install pandoc-fignos #pandoc filter for numbering figures
  - sudo pip install pandoc-eqnos #pandoc filter for numbering equations
  - sudo pip install pandoc-tablenos #pandoc filter for numbering tables
  - wget `curl https://api.github.com/repos/jgm/pandoc/releases/latest | jq -r '.assets[] | .browser_download_url | select(endswith("deb"))'` -O pandoc.deb
  - sudo dpkg -i pandoc.deb  #new pandoc version
  - tlmgr update --self
  - tlmgr update --all
sudo: true
script: 
  - mkdir build
  - cd Handbook
  - make all
  - zip -r ./Exports/Hall_Handbook_html.zip ./Exports/Media ./Exports/Hall_Handbook.html  
  - cd Exports && ls
notifications:
  slack: fermiumlabs:0BfrFyD9uqr9bFhsH0Etn4wo
  email: false
deploy:
  provider: releases
  api_key:
    secure: hnYQIAqK1XOzXzVBa+wtgHFWORiiwVBjKBNRqw7t3VPyzxQQL84SAtaMVre0B7HGzHUGYC7MQdXUGe/Yh15dbu4/oAeA3MNNVcl5ou+Ixu3snZiH4x7097kGXh3EbbFBFZ9aNiJ78vnH3k0jtH8ft8e$
  file: 
    - Hall_Handbook.pdf
    - Hall_Handbook_html.zip
    - Hall_Handbook.docx
  skip_cleanup: true
  on:
    tags: true
