language: c
install:
  - sudo apt-get update
  - sudo apt-get -y install jq
  - sudo apt-get -y install python-pip
  - sudo pip install --upgrade pip
  - sudo pip install pandoc-fignos
  - sudo pip install pandoc-eqnos
  - sudo pip install pandoc-tablenos
  - wget `curl https://api.github.com/repos/jgm/pandoc/releases/latest | jq -r '.assets[] | .browser_download_url | select(endswith("deb"))'` -O pandoc.deb
  - sudo dpkg -i pandoc.deb
  - mkdir build
  - wget -O ./build/install-tl-ubuntu https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu 
  - chmod +x ./build/install-tl-ubuntu
  - sudo ./build/install-tl-ubuntu
  - sudo /opt/texbin/tlmgr update --self
  - sudo /opt/texbin/tlmgr update --all
  - sudo /opt/texbin/tlmgr install xetex
  - sudo /opt/texbin/tlmgr install siunitx
  - sudo /opt/texbin/tlmgr install collection-fontsrecommended
  - sudo /opt/texbin/tlmgr install tufte-latex
  - sudo /opt/texbin/tlmgr install changepage
  - sudo /opt/texbin/tlmgr install paralist
  - sudo /opt/texbin/tlmgr install titlesec
  - sudo /opt/texbin/tlmgr install ec
  - sudo /opt/texbin/tlmgr install units
  - sudo /opt/texbin/tlmgr install lipsum
  - sudo /opt/texbin/tlmgr install mathpazo
  - sudo /opt/texbin/tlmgr install fpl
  - sudo /opt/texbin/tlmgr install ucs
  - sudo /opt/texbin/tlmgr install etoolbox
  - sudo /opt/texbin/tlmgr install fancyhdr
  - sudo /opt/texbin/tlmgr install graphics
  - sudo /opt/texbin/tlmgr install lmodern
  - sudo /opt/texbin/tlmgr install setspace
  - sudo /opt/texbin/tlmgr install amssymb
  - sudo /opt/texbin/tlmgr install amsmath
  - sudo /opt/texbin/tlmgr install ifxetex
  - sudo /opt/texbin/tlmgr install ifluatex
  - sudo /opt/texbin/tlmgr install T1
  - sudo /opt/texbin/tlmgr install fontenc
  - sudo /opt/texbin/tlmgr install inputenc
  - sudo /opt/texbin/tlmgr install eurosym
  - sudo /opt/texbin/tlmgr install mathspec
  - sudo /opt/texbin/tlmgr install fontspec
  - sudo /opt/texbin/tlmgr install upquote
  - sudo /opt/texbin/tlmgr install microtype
  - sudo /opt/texbin/tlmgr install geometry
  - sudo /opt/texbin/tlmgr install hyperref
  - sudo /opt/texbin/tlmgr install sep
  - sudo /opt/texbin/tlmgr install babel-lang
  - sudo /opt/texbin/tlmgr install polyglossia
  - sudo /opt/texbin/tlmgr install natbi
  - sudo /opt/texbin/tlmgr install bbiblatex
  - sudo /opt/texbin/tlmgr install listings
  - sudo /opt/texbin/tlmgr install fancyvrb
  - sudo /opt/texbin/tlmgr install longtable
  - sudo /opt/texbin/tlmgr install booktabs
  - sudo /opt/texbin/tlmgr install grffile
  - sudo /opt/texbin/tlmgr install ulem
  - sudo /opt/texbin/tlmgr install parskip
  - sudo /opt/texbin/tlmgr install bidi
  - sudo apt-get -y install zip
sudo: true
script: 
  - cd Handbook && make all
  - mv Handbook/Exports/ ./build
  - zip -r ./build/Hall_Handbook_html.zip ./build/Media ./build/Hall_Handbook.html  
notifications:
  slack: fermiumlabs:0BfrFyD9uqr9bFhsH0Etn4wo
  email: false
deploy:
  provider: releases
  api_key:
    secure: hnYQIAqK1XOzXzVBa+wtgHFWORiiwVBjKBNRqw7t3VPyzxQQL84SAtaMVre0B7HGzHUGYC7MQdXUGe/Yh15dbu4/oAeA3MNNVcl5ou+Ixu3snZiH4x7097kGXh3EbbFBFZ9aNiJ78vnH3k0jtH8ft8e$
  file: 
    - build/Hall_Handbook.pdf
    - build/Hall_Handbook_html.zip
    - build/Hall_Handbook.docx
  on:
    repo: fermiumlabs/Hall-effect-apparatus
