language: R
install:
  - sudo apt-get update
  - sudo apt-get -y install jq python-pip zip
  - sudo apt-get -y remove pandoc
  - sudo pip install --upgrade pip
  - sudo pip install pandoc-fignos
  - sudo pip install pandoc-eqnos
  - sudo pip install pandoc-tablenos
  - wget `curl https://api.github.com/repos/jgm/pandoc/releases/latest | jq -r '.assets[] | .browser_download_url | select(endswith("deb"))'` -O pandoc.deb
  - sudo dpkg -i pandoc.deb
  - tlmgr update --self
  - tlmgr update --all
sudo: true
script:
  - mkdir build
  - cd Handbook
  - make all
  - zip -r ./Exports/Hall_Handbook_html.zip ./Exports/Media ./Exports/Hall_Handbook.html
  - cd Exports && ls
notifications:
  slack: fermiumlabs:0BfrFyD9uqr9bFhsH0Etn4wo
  email: false
deploy:
  provider: releases
  api_key:
    secure: X6L1ozlHXnDE1yhwCIppWTRUCYxQ7kH1BeDc/NXj7o52PXKOTF+4NodNrU+NYeCBuZ1fGMyfHnGxjoiXqEWHR7ENZjSfu/dUC1UWZjFtYRrmf/kGbChT6TC4Sc4VWSS3oCliD7tWirCV5acT0mysHfo+ucyHAGCXOB7EXAY0s6a61+x0/TfYAYhU+dF7+SrXSybdLsUPLiueX7pQ3rxQu/2mPyQs1FO98j79gPxSOcILn+SOIaEUQaJRJVUTmaXWBC3kNFr0pLXwqdkNtybEuvCqwSQ0gPzQj1CtMb8gLTYUP8BZAxCX/CGiwit+PkWPPHuOMEh7v4mLIifWvA2Dy9C36xcXBQXGsPNfjZj1OGH6N6wvgx0pzZyrODV2hIAKxJONwS1NrkceuzplXvkJPd7mwYo78oRYmLtQmOdnLQFiymMlEqAelRX0ruQNNdGI+yl5cnteTzRqpFpo/ZIu0xrNMviUb69lzSjYxQmVxQkVQ0Dil7vKzs8fh0GFqHPJ/ZzsbVtS19LfRavdn68LTjYFGP+nrJaLkf7vkwzkvC+DrXyiwvbrEq2ktsphOE0roUirR+mfqr/awnEJGpwLY5C6oRpdPVLHDBWbgsCz9rbJTjfGUIhuG+soQa6YAOKBTeS5yTr7ovNNeut1INzChD9s7dh4APbE+cZ03ekeB/Y=
  file: 
    - Hall_Handbook.pdf
    - Hall_Handbook_html.zip
    - Hall_Handbook.docx
  on:
    repo: fermiumlabs/Hall-effect-apparatus
    branch: travis-ci
  skip_cleanup: true
