language: c
install:
  - sudo apt-get update
  - sudo apt-get -y install jq
  - sudo apt-get -y install python-pip
  - sudo pip install --upgrade pip
  - sudo pip install pandoc-fignos
  - sudo pip install pandoc-eqnos
  - sudo pip install pandoc-tablenos
  - wget `curl https://api.github.com/repos/jgm/pandoc/releases/latest | jq -r '.assets[] | .browser_download_url | select(endswith("deb"))'` -O pandoc.deb
  - sudo dpkg -i pandoc.deb
  - mkdir build
  - wget -O ./build/install-tl-ubuntu https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu 
  - chmod +x ./build/install-tl-ubuntu
  - sudo ./build/install-tl-ubuntu
  - sudo /opt/texbin/tlmgr update --self
  - sudo /opt/texbin/tlmgr update --all
  - sudo /opt/texbin/tlmgr install xetex
  - sudo /opt/texbin/tlmgr install siunitx
  - sudo /opt/texbin/tlmgr install collection-fontsrecommended
  - sudo /opt/texbin/tlmgr install tufte-latex
  - sudo /opt/texbin/tlmgr install changepage
  - sudo /opt/texbin/tlmgr install paralist
  - sudo /opt/texbin/tlmgr install titlesec
  - sudo /opt/texbin/tlmgr install ec
  - sudo /opt/texbin/tlmgr install units
  - sudo /opt/texbin/tlmgr install lipsum
  - sudo /opt/texbin/tlmgr install mathpazo
  - sudo /opt/texbin/tlmgr install fpl
  - sudo /opt/texbin/tlmgr install ucs
  - sudo /opt/texbin/tlmgr install etoolbox
  - sudo /opt/texbin/tlmgr install fancyhdr
  - sudo /opt/texbin/tlmgr install graphicx
  - sudo /opt/texbin/tlmgr installl modern
  - sudo /opt/texbin/tlmgr installl setspaceamssymb
  - sudo /opt/texbin/tlmgr installl amsmath
  - sudo /opt/texbin/tlmgr installl ifxetex
  - sudo /opt/texbin/tlmgr installl ifluatex
  - sudo /opt/texbin/tlmgr installl T1
  - sudo /opt/texbin/tlmgr installl fontenc
  - sudo /opt/texbin/tlmgr installl inputenc
  - sudo /opt/texbin/tlmgr installl eurosym
  - sudo /opt/texbin/tlmgr installl mathspec
  - sudo /opt/texbin/tlmgr installl fontspec
  - sudo /opt/texbin/tlmgr installl upquote
  - sudo /opt/texbin/tlmgr installl microtype
  - sudo /opt/texbin/tlmgr installl geometry
  - sudo /opt/texbin/tlmgr installl hyperref
  - sudo /opt/texbin/tlmgr installl sep
  - sudo /opt/texbin/tlmgr installl babel-lang
  - sudo /opt/texbin/tlmgr installl polyglossia
  - sudo /opt/texbin/tlmgr installl  natbi
  - sudo /opt/texbin/tlmgr installl bbiblatex
  - sudo /opt/texbin/tlmgr installl listings
  - sudo /opt/texbin/tlmgr installl fancyvrb
  - sudo /opt/texbin/tlmgr installl longtable
  - sudo /opt/texbin/tlmgr installl booktabsgraphicx
  - sudo /opt/texbin/tlmgr installl grffileulemparskip
  - sudo /opt/texbin/tlmgr installl bidi
  - sudo apt-get -y install zip
sudo: true
script: 
  - cd Handbook && make all
  - mv Handbook/Exports/ ./build
  - zip -r ./build/Hall_Handbook_html.zip ./build/Media ./build/Hall_Handbook.html  
notifications:
  slack: fermiumlabs:0BfrFyD9uqr9bFhsH0Etn4wo
deploy:
  provider: releases
  api_key:
    secure: hnYQIAqK1XOzXzVBa+wtgHFWORiiwVBjKBNRqw7t3VPyzxQQL84SAtaMVre0B7HGzHUGYC7MQdXUGe/Yh15dbu4/oAeA3MNNVcl5ou+Ixu3snZiH4x7097kGXh3EbbFBFZ9aNiJ78vnH3k0jtH8ft8e$
  file: 
    - build/Hall_Handbook.pdf
    - build/Hall_Handbook_html.zip
    - build/Hall_Handbook.docx
  on:
    repo: fermiumlabs/Hall-effect-apparatus
